### PR TITLE
Configuration block

### PR DESCRIPTION
**Pull request by davideluque**

### CODE REVIEW

**Comment by davideluque** [comment]
Inspiration from http://lizabinante.com/blog/creating-a-configurable-ruby-gem/

**Review by ludvigandersen — COMMENTED** [review]
With this code, will we then be able to have a nemid.rb config file and write:
```
NemID.configure do |config|
    config.oces_cert = "some_cert"
end
```
?

**Comment by davideluque** [comment]
> With this code, will we then be able to have a nemid.rb config file and write:
> 
> ```
> NemID.configure do |config|
>     config.oces_cert = "some_cert"
> end
> ```
> 
> ?

Yes, it will work in a Rails initializer. It also works the same way outside rails.

I am adding this to the README.

**Review by ludvigandersen — APPROVED** [review]
I tested the implementation using the PidCprMatch service and got the expected response 403.
I configured and accessed the config as shown below, is this correct? I've approved it since i got it working just fine.

nemid-config

The NemID config is retrieved in the pid_cpr_match.rb file:
nemid-config-access

**Pull request merged**
