### PR TITLE
Improve certificate and key reading

### PR DESCRIPTION
**Pull request by davideluque**
**Two reasons to implement this feature:**

First, this PR adds a performance improvement to the library: the PKCS #12 file was read every time the `Crypto` class was initialized. The crypto class was initialized when client initialization parameters were requested or when matching PIDs to CPRs.  I/O operations are extremely expensive.

Second, I found out that storing as a file the PKCS #12 in our Rails application was quite bothersome since we do not want to 
upload the file to the CVS, hindering the Continuous Integration pipeline, quick deployment, certificate replacing, among others.

**If not as files, how then?**

The definition of a PKCS #12 file, according to Wikipedia:

> PKCS #12 defines an archive file format for storing many cryptography objects as a single file. It is commonly used to bundle a private key with its X.509 certificate or to bundle all the members of a chain of trust.

With openssl we can export from the PKCS #12 file the X.509 certificate(s) and the private key. 

As of right now, the end-entity certificate (leaf certificate) and the private key are the only two objects that we need to generate client initialization parameters and to make PID-CPR requests.

Now, according to ssh.com, this is the purpose of the password:

image

I was able to generate client initialization parameters without providing the password, and I would consider `signing` as "using" the private key. I am thinking that this is because once you have exported the key to .pem format you already passed the password requirement, so one should be careful about where the private key is stored, a suggestion is to store it in the encrypted credentials. 

This is also not a new practice, Apple Sign In requires storing their private key in the backend application order to sign parameters.

### CODE REVIEW

**Comment by davideluque** [comment]
Please checkout to this branch and validate if the PID-CPR service works with the new way the private key is provided. Only if you are going to be in a place where the IP address is allowed to perform requests.

I am also gonna try to add some tests to this branch if I have time and try the same but with the encrypted private key instead of the plain private key.

**Comment by davideluque** [comment]
To-do:

- Fill readme with an explanation about how to export the certificate and key.

**Comment by davideluque** [comment]
For now, we are sticking with the non-encrypted private key.

I am not adding tests since I need to check how to generate certificates and keys to use in testing that are similar copies to the ones issued by NemID.

Ready for review @ludvigandersen

**Comment by davideluque** [comment]
This PR when merged automatically stales #9

**Review by ludvigandersen — APPROVED** [review]
Works with pid_cpr aswell.

**Pull request merged**
